"""initial schema

迁移说明
--------
* 为什么需要这次变更：
    建立 P1 记账核心闭环的全部基础表 —— 币种、账户、分类、标签、项目、
    成员、流水、分账、流水-标签关联、应用级设置与审计日志。
* 对既有数据的影响：
    **无**。这是首个迁移，只对空库执行（P0 阶段尚未建立数据库）。
* 是否可回滚：
    是。downgrade 会删除全部 11 张表及其索引。
    ⚠️ 回滚会**丢失所有账目数据**，仅用于开发期重置，生产环境不要执行。
* 关键设计（详见 docs/DATA_MODEL.md）：
    - 金额一律 ``*_minor`` 整数最小单位，无浮点参与；
    - ``occurred_at`` 是**本地墙钟**（业务时间），``created_at`` 等是 UTC（审计时间）；
    - 软删除用 ``deleted_at``，并用**部分唯一索引**
      （``sqlite_where=deleted_at IS NULL``）实现"删除后可重建同名"；
    - ``direction`` 与 ``type`` 必须自洽（支出=out、收入=in），
      使余额公式无需按类型分支；
    - 转账必须成对：CHECK 保证 ``type='transfer'`` 时有目标账户且不等于源账户；
    - ``external_id`` 唯一索引用于导入去重（SQLite 中多个 NULL 互不冲突，
      因此手写流水不受影响）。

Revision ID: 37970cc9629c
Revises:
Create Date: 2026-10-01 09:57:08.355272
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "37970cc9629c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=24), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column(
            "initial_balance_minor", sa.BigInteger(), nullable=False, comment="建账起点余额（最小单位）"
        ),
        sa.Column("icon", sa.String(length=48), nullable=False),
        sa.Column("color", sa.String(length=16), nullable=False),
        sa.Column("institution", sa.String(length=64), nullable=False, comment="银行/机构名"),
        sa.Column("card_no_tail", sa.String(length=8), nullable=False, comment="卡号后四位"),
        sa.Column("credit_limit_minor", sa.BigInteger(), nullable=False),
        sa.Column("bill_day", sa.Integer(), nullable=True, comment="账单日（1-28）"),
        sa.Column("due_day", sa.Integer(), nullable=True, comment="还款日（1-28）"),
        sa.Column("include_in_net_worth", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="软删除时间（UTC）；NULL 表示未删除"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
    )
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_accounts_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index("ix_accounts_sort", ["sort_order", "id"], unique=False)
        batch_op.create_index("ix_accounts_type", ["type"], unique=False)
        batch_op.create_index(
            "uq_accounts_name_active", ["name"], unique=True, sqlite_where=sa.text("deleted_at IS NULL")
        )

    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_app_settings")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entity", sa.String(length=32), nullable=False, comment="表名/实体名"),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=16), nullable=False, comment="create/update/delete/restore"),
        sa.Column("changes", sa.JSON(), nullable=False),
        sa.Column("actor", sa.String(length=32), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index("ix_audit_created", ["created_at"], unique=False)
        batch_op.create_index("ix_audit_entity", ["entity", "entity_id", "created_at"], unique=False)

    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("path", sa.String(length=255), nullable=False, comment="物化路径 /1/7/23"),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("icon", sa.String(length=48), nullable=False),
        sa.Column("color", sa.String(length=16), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False, comment="内置分类：可改可隐藏，但不可删除"),
        sa.Column("is_hidden", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="软删除时间（UTC）；NULL 表示未删除"),
        sa.CheckConstraint("depth >= 0 AND depth <= 5", name=op.f("ck_categories_depth_range")),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_categories_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index("ix_categories_kind", ["kind"], unique=False)
        batch_op.create_index("ix_categories_parent", ["parent_id", "sort_order"], unique=False)
        batch_op.create_index("ix_categories_path", ["path"], unique=False)

    op.create_table(
        "currencies",
        sa.Column("code", sa.String(length=8), nullable=False, comment="ISO 代码，如 CNY"),
        sa.Column("name", sa.String(length=32), nullable=False, comment="显示名"),
        sa.Column("symbol", sa.String(length=8), nullable=False, comment="符号"),
        sa.Column("minor_units", sa.Integer(), nullable=False, comment="最小单位位数"),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_currencies")),
    )
    op.create_table(
        "members",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=48), nullable=False),
        sa.Column("color", sa.String(length=16), nullable=False),
        sa.Column("is_self", sa.Boolean(), nullable=False, comment="是否为账本主人"),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="软删除时间（UTC）；NULL 表示未删除"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_members")),
    )
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_members_deleted_at"), ["deleted_at"], unique=False)

    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("color", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("budget_minor", sa.BigInteger(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="软删除时间（UTC）；NULL 表示未删除"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_projects_deleted_at"), ["deleted_at"], unique=False)

    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=48), nullable=False),
        sa.Column("color", sa.String(length=16), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="软删除时间（UTC）；NULL 表示未删除"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
    )
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tags_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(
            "uq_tags_name_active", ["name"], unique=True, sqlite_where=sa.text("deleted_at IS NULL")
        )

    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("direction", sa.String(length=4), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False, comment="发生时间（本地墙钟）"),
        sa.Column("tz_offset_minutes", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("to_account_id", sa.Integer(), nullable=True, comment="转账目标账户"),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False, comment="金额（最小单位，恒正）"),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("base_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("payee", sa.String(length=96), nullable=False, comment="商户/对方"),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="软删除时间（UTC）；NULL 表示未删除"),
        sa.CheckConstraint(
            "(type = 'expense' AND direction = 'out') OR (type = 'income' AND direction = 'in') OR type IN ('transfer', 'adjust')",
            name=op.f("ck_transactions_direction_matches_type"),
        ),
        sa.CheckConstraint(
            "(type = 'transfer' AND to_account_id IS NOT NULL AND to_account_id <> account_id) OR (type <> 'transfer' AND to_account_id IS NULL)",
            name=op.f("ck_transactions_transfer_target"),
        ),
        sa.CheckConstraint("direction IN ('in', 'out')", name=op.f("ck_transactions_direction_domain")),
        sa.CheckConstraint("amount_minor > 0", name=op.f("ck_transactions_amount_positive")),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_transactions_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_transactions_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"], ["members.id"], name=op.f("fk_transactions_member_id_members"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_transactions_project_id_projects"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["to_account_id"],
            ["accounts.id"],
            name=op.f("fk_transactions_to_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
    )
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_index("ix_transactions_account_occurred", ["account_id", "occurred_at"], unique=False)
        batch_op.create_index(
            "ix_transactions_category_occurred", ["category_id", "occurred_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_transactions_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index("ix_transactions_occurred", ["occurred_at"], unique=False)
        batch_op.create_index("uq_transactions_external", ["external_id"], unique=True)

    op.create_table(
        "transaction_splits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("note", sa.String(length=128), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.CheckConstraint("amount_minor > 0", name=op.f("ck_transaction_splits_split_amount_positive")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_transaction_splits_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_transaction_splits_transaction_id_transactions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transaction_splits")),
    )
    with op.batch_alter_table("transaction_splits", schema=None) as batch_op:
        batch_op.create_index("ix_splits_transaction", ["transaction_id", "sort_order"], unique=False)

    op.create_table(
        "transaction_tags",
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_transaction_tags_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_transaction_tags_transaction_id_transactions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("transaction_id", "tag_id", name=op.f("pk_transaction_tags")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction_tags")
    with op.batch_alter_table("transaction_splits", schema=None) as batch_op:
        batch_op.drop_index("ix_splits_transaction")

    op.drop_table("transaction_splits")
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index("uq_transactions_external")
        batch_op.drop_index("ix_transactions_occurred")
        batch_op.drop_index(batch_op.f("ix_transactions_deleted_at"))
        batch_op.drop_index("ix_transactions_category_occurred")
        batch_op.drop_index("ix_transactions_account_occurred")

    op.drop_table("transactions")
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_index("uq_tags_name_active", sqlite_where=sa.text("deleted_at IS NULL"))
        batch_op.drop_index(batch_op.f("ix_tags_deleted_at"))

    op.drop_table("tags")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projects_deleted_at"))

    op.drop_table("projects")
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_members_deleted_at"))

    op.drop_table("members")
    op.drop_table("currencies")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index("ix_categories_path")
        batch_op.drop_index("ix_categories_parent")
        batch_op.drop_index("ix_categories_kind")
        batch_op.drop_index(batch_op.f("ix_categories_deleted_at"))

    op.drop_table("categories")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_entity")
        batch_op.drop_index("ix_audit_created")

    op.drop_table("audit_log")
    op.drop_table("app_settings")
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_index("uq_accounts_name_active", sqlite_where=sa.text("deleted_at IS NULL"))
        batch_op.drop_index("ix_accounts_type")
        batch_op.drop_index("ix_accounts_sort")
        batch_op.drop_index(batch_op.f("ix_accounts_deleted_at"))

    op.drop_table("accounts")
    # ### end Alembic commands ###
