"""p6 workdays paydays payroll

迁移说明（自动生成后请手工补齐）
--------------------------------
* 为什么需要这次变更：
* 对既有数据的影响：
* 是否可回滚（downgrade 是否真的实现了）：

Revision ID: 3dbc51d5db59
Revises: 763330518736
Create Date: 2026-10-01 21:48:22.272585
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3dbc51d5db59"
down_revision: str | None = "763330518736"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workday_calendar",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("is_workday", sa.Boolean(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.CheckConstraint(
            "kind IN ('holiday', 'makeup_workday', 'custom_rest', 'custom_workday')",
            name=op.f("ck_workday_calendar_kind"),
        ),
        sa.CheckConstraint(
            "source IN ('builtin', 'user_import', 'user_edit')", name=op.f("ck_workday_calendar_source")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workday_calendar")),
    )
    with op.batch_alter_table("workday_calendar", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workday_calendar_day"), ["day"], unique=True)

    op.create_table(
        "pay_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("employer", sa.String(length=80), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="软删除时间（UTC）；NULL 表示未删除"),
        sa.CheckConstraint(
            "kind IN ('salary', 'part_time', 'bonus', 'investment', 'rent', 'other')",
            name=op.f("ck_pay_sources_kind"),
        ),
        sa.CheckConstraint("priority BETWEEN 0 AND 9", name=op.f("ck_pay_sources_priority")),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_pay_sources_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name=op.f("fk_pay_sources_category_id_categories")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pay_sources")),
    )
    with op.batch_alter_table("pay_sources", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pay_sources_deleted_at"), ["deleted_at"], unique=False)

    op.create_table(
        "pay_components",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=48), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("calc", sa.String(length=12), nullable=False),
        sa.Column("sign", sa.Integer(), nullable=False),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("base_key", sa.String(length=16), nullable=False),
        sa.Column("rate_bps", sa.Integer(), nullable=False),
        sa.Column("formula", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.CheckConstraint("calc IN ('fixed', 'ratio', 'formula')", name=op.f("ck_pay_components_calc")),
        sa.CheckConstraint(
            "kind IN ('basic', 'performance', 'overtime', 'meal', 'transport', 'bonus', 'commission', 'reimbursement', 'pretax_deduction', 'tax', 'insurance', 'other')",
            name=op.f("ck_pay_components_kind"),
        ),
        sa.CheckConstraint("amount_minor >= 0", name=op.f("ck_pay_components_amount")),
        sa.CheckConstraint("rate_bps BETWEEN 0 AND 100000", name=op.f("ck_pay_components_rate")),
        sa.CheckConstraint("sign IN (1, -1)", name=op.f("ck_pay_components_sign")),
        sa.ForeignKeyConstraint(
            ["source_id"], ["pay_sources.id"], name=op.f("fk_pay_components_source_id_pay_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pay_components")),
    )
    with op.batch_alter_table("pay_components", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pay_components_source_id"), ["source_id"], unique=False)

    op.create_table(
        "payday_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("day_of_month", sa.Integer(), nullable=False),
        sa.Column("day_kind", sa.String(length=16), nullable=False),
        sa.Column("nth", sa.Integer(), nullable=False),
        sa.Column("weekend_policy", sa.String(length=12), nullable=False),
        sa.Column("holiday_policy", sa.String(length=12), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("remind_at", sa.String(length=5), nullable=False),
        sa.Column("grace_days", sa.Integer(), nullable=False),
        sa.Column("require_form", sa.Boolean(), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.CheckConstraint(
            "day_kind IN ('fixed', 'month_end', 'last_workday', 'nth_workday')",
            name=op.f("ck_payday_rules_day_kind"),
        ),
        sa.CheckConstraint(
            "holiday_policy IN ('advance', 'postpone', 'none')", name=op.f("ck_payday_rules_holiday_policy")
        ),
        sa.CheckConstraint(
            "weekend_policy IN ('advance', 'postpone', 'none')", name=op.f("ck_payday_rules_weekend_policy")
        ),
        sa.CheckConstraint("grace_days BETWEEN 0 AND 30", name=op.f("ck_payday_rules_grace")),
        sa.ForeignKeyConstraint(
            ["source_id"], ["pay_sources.id"], name=op.f("fk_payday_rules_source_id_pay_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payday_rules")),
    )
    with op.batch_alter_table("payday_rules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payday_rules_source_id"), ["source_id"], unique=False)

    op.create_table(
        "payroll_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("pay_date", sa.Date(), nullable=False),
        sa.Column("gross_minor", sa.Integer(), nullable=False),
        sa.Column("net_minor", sa.Integer(), nullable=False),
        sa.Column("items", sa.JSON(), nullable=False),
        sa.Column("insurance_snapshot", sa.JSON(), nullable=False),
        sa.Column("tax_minor", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("skip_reason", sa.String(length=200), nullable=False),
        sa.Column("filled_at", sa.DateTime(), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="软删除时间（UTC）；NULL 表示未删除"),
        sa.CheckConstraint(
            "status IN ('draft', 'filled', 'skipped')", name=op.f("ck_payroll_records_status")
        ),
        sa.CheckConstraint("gross_minor >= 0 AND net_minor >= 0", name=op.f("ck_payroll_records_amounts")),
        sa.ForeignKeyConstraint(
            ["source_id"], ["pay_sources.id"], name=op.f("fk_payroll_records_source_id_pay_sources")
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_payroll_records_transaction_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payroll_records")),
    )
    with op.batch_alter_table("payroll_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payroll_records_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_payroll_records_period"), ["period"], unique=False)
        batch_op.create_index(batch_op.f("ix_payroll_records_source_id"), ["source_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payroll_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payroll_records_source_id"))
        batch_op.drop_index(batch_op.f("ix_payroll_records_period"))
        batch_op.drop_index(batch_op.f("ix_payroll_records_deleted_at"))

    op.drop_table("payroll_records")
    with op.batch_alter_table("payday_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payday_rules_source_id"))

    op.drop_table("payday_rules")
    with op.batch_alter_table("pay_components", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pay_components_source_id"))

    op.drop_table("pay_components")
    with op.batch_alter_table("pay_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pay_sources_deleted_at"))

    op.drop_table("pay_sources")
    with op.batch_alter_table("workday_calendar", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workday_calendar_day"))

    op.drop_table("workday_calendar")
    # ### end Alembic commands ###
