"""p6 scheduler tasks prompts notifications

迁移说明（自动生成后请手工补齐）
--------------------------------
* 为什么需要这次变更：
* 对既有数据的影响：
* 是否可回滚（downgrade 是否真的实现了）：

Revision ID: 6b308efaafa3
Revises: 98dfc6d2c979
Create Date: 2026-10-01 22:33:12.298420
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6b308efaafa3"
down_revision: str | None = "98dfc6d2c979"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(length=8), nullable=False),
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column("body", sa.String(length=400), nullable=False),
        sa.Column("action_path", sa.String(length=120), nullable=False),
        sa.Column("action_label", sa.String(length=32), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column("dedupe_key", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.CheckConstraint(
            "level IN ('info', 'success', 'warn', 'error')", name=op.f("ck_notifications_level")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notifications_dedupe_key"), ["dedupe_key"], unique=False)

    op.create_table(
        "pending_prompts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column("body", sa.String(length=400), nullable=False),
        sa.Column("blocking_level", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("target_kind", sa.String(length=24), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=True),
        sa.Column("snooze_count", sa.Integer(), nullable=False),
        sa.Column("max_snooze", sa.Integer(), nullable=False),
        sa.Column("next_remind_at", sa.DateTime(), nullable=True),
        sa.Column("skip_reason", sa.String(length=200), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("dedupe_key", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.CheckConstraint(
            "blocking_level IN ('strong', 'normal')", name=op.f("ck_pending_prompts_blocking_level")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'snoozed', 'resolved', 'skipped')", name=op.f("ck_pending_prompts_status")
        ),
        sa.CheckConstraint("snooze_count >= 0 AND max_snooze >= 0", name=op.f("ck_pending_prompts_snooze")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pending_prompts")),
    )
    with op.batch_alter_table("pending_prompts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pending_prompts_dedupe_key"), ["dedupe_key"], unique=False)

    op.create_table(
        "scheduled_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("rule", sa.JSON(), nullable=False),
        sa.Column("catch_up_policy", sa.String(length=12), nullable=False),
        sa.Column("next_run_at", sa.DateTime(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("ref_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.CheckConstraint(
            "catch_up_policy IN ('startup', 'immediate', 'record_only')",
            name=op.f("ck_scheduled_tasks_catch_up"),
        ),
        sa.CheckConstraint(
            "kind IN ('payday', 'insurance', 'bill', 'repayment', 'recurring', 'budget_close', 'report', 'backup', 'custom')",
            name=op.f("ck_scheduled_tasks_kind"),
        ),
        sa.CheckConstraint("priority BETWEEN 0 AND 9", name=op.f("ck_scheduled_tasks_priority")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduled_tasks")),
        sa.UniqueConstraint("code", name="uq_scheduled_tasks_code"),
    )
    op.create_table(
        "task_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("summary", sa.String(length=200), nullable=False),
        sa.Column("error", sa.String(length=300), nullable=False),
        sa.Column("caught_up", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.CheckConstraint(
            "status IN ('success', 'skipped', 'failed', 'caught_up')", name=op.f("ck_task_runs_status")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["scheduled_tasks.id"], name=op.f("fk_task_runs_task_id_scheduled_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_runs")),
    )
    with op.batch_alter_table("task_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_task_runs_task_id"), ["task_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_runs_task_id"))

    op.drop_table("task_runs")
    op.drop_table("scheduled_tasks")
    with op.batch_alter_table("pending_prompts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pending_prompts_dedupe_key"))

    op.drop_table("pending_prompts")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_dedupe_key"))

    op.drop_table("notifications")
    # ### end Alembic commands ###
