"""p1 transaction templates

迁移说明
--------
* 为什么需要这次变更：P1 收尾的「快捷记账增强」需要一个模板表，
  把一整套记账字段存下来供一键填充；
* 对既有数据的影响：**无**。只新增一张表，不修改任何既有列；
* 是否可回滚：可以。``downgrade`` 删除 ``transaction_templates``。
  代价是丢掉模板（模板不是账目事实，不影响任何已记录的流水）。

Revision ID: 6c353d2fb395
Revises: cc8294c3ca9b
Create Date: 2026-10-01 13:45:29.482219
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6c353d2fb395"
down_revision: str | None = "cc8294c3ca9b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=48), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("to_account_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("amount_minor", sa.Integer(), nullable=True, comment="为空表示只填结构，金额每次手输"),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("payee", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("tag_ids", sa.Text(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="软删除时间（UTC）；NULL 表示未删除"),
        sa.CheckConstraint(
            "type IN ('expense', 'income', 'transfer')", name=op.f("ck_transaction_templates_type")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_transaction_templates_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name=op.f("fk_transaction_templates_category_id_categories")
        ),
        sa.ForeignKeyConstraint(
            ["member_id"], ["members.id"], name=op.f("fk_transaction_templates_member_id_members")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_transaction_templates_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["to_account_id"], ["accounts.id"], name=op.f("fk_transaction_templates_to_account_id_accounts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transaction_templates")),
    )
    with op.batch_alter_table("transaction_templates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_transaction_templates_deleted_at"), ["deleted_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction_templates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transaction_templates_deleted_at"))

    op.drop_table("transaction_templates")
    # ### end Alembic commands ###
