"""p1 attachments

迁移说明
--------
* 为什么需要这次变更：P1 的「详细填表」里附件一直没做（此前记为随 P8），
  本轮补齐。新增一张 ``attachments`` 表存元数据，文件本身落在
  ``<data>/attachments/`` 下 —— 数据库里只存**相对引用**，
  这样数据目录被搬走（便携模式、换盘、恢复备份）时什么都不用改；
* 对既有数据的影响：**无**。只新增一张表；
* 是否可回滚：可以。``downgrade`` 删除 ``attachments``。
  代价是丢掉附件记录 —— **磁盘上的文件不会被删**（刻意如此：
  迁移回滚不该静默删用户文件），孤儿文件可以手工清理。

Revision ID: 6c9fb8b83d3a
Revises: aaa215176dc4
Create Date: 2026-10-01 16:25:24.370008
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6c9fb8b83d3a"
down_revision: str | None = "aaa215176dc4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=12), nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=True),
        sa.Column("card_artwork_id", sa.Integer(), nullable=True),
        sa.Column("file_ref", sa.String(length=200), nullable=False),
        sa.Column("original_name", sa.String(length=200), nullable=False),
        sa.Column("mime", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.CheckConstraint("kind IN ('transaction', 'card')", name=op.f("ck_attachments_kind")),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_attachments_size")),
        sa.ForeignKeyConstraint(
            ["card_artwork_id"],
            ["card_artworks.id"],
            name=op.f("fk_attachments_card_artwork_id_card_artworks"),
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"], ["transactions.id"], name=op.f("fk_attachments_transaction_id_transactions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
    )
    with op.batch_alter_table("attachments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_attachments_card_artwork_id"), ["card_artwork_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_attachments_transaction_id"), ["transaction_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attachments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attachments_transaction_id"))
        batch_op.drop_index(batch_op.f("ix_attachments_card_artwork_id"))

    op.drop_table("attachments")
    # ### end Alembic commands ###
