"""p5 ai analyses

迁移说明（自动生成后请手工补齐）
--------------------------------
* 为什么需要这次变更：
* 对既有数据的影响：
* 是否可回滚（downgrade 是否真的实现了）：

Revision ID: 763330518736
Revises: 883ebd14da2d
Create Date: 2026-10-01 21:17:58.200595
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "763330518736"
down_revision: str | None = "883ebd14da2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_kind", sa.String(length=16), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("redacted", sa.Boolean(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("fallback_reason", sa.String(length=24), nullable=False),
        sa.Column("error", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.CheckConstraint("source IN ('online', 'offline')", name=op.f("ck_ai_analyses_source")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_analyses")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ai_analyses")
    # ### end Alembic commands ###
