"""p4 piggy banks and goals

迁移说明（自动生成后请手工补齐）
--------------------------------
* 为什么需要这次变更：
* 对既有数据的影响：
* 是否可回滚（downgrade 是否真的实现了）：

Revision ID: 883ebd14da2d
Revises: 6c9fb8b83d3a
Create Date: 2026-10-01 17:46:38.989362
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "883ebd14da2d"
down_revision: str | None = "6c9fb8b83d3a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "goals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("target_amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("hide_amount", sa.Boolean(), nullable=False),
        sa.Column("achieved_at", sa.DateTime(), nullable=True),
        sa.Column("celebrated", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="软删除时间（UTC）；NULL 表示未删除"),
        sa.CheckConstraint(
            "kind IN ('purchase', 'emergency', 'travel', 'education', 'other')", name=op.f("ck_goals_kind")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'achieved', 'paused', 'abandoned')", name=op.f("ck_goals_status")
        ),
        sa.CheckConstraint("priority BETWEEN 0 AND 9", name=op.f("ck_goals_priority")),
        sa.CheckConstraint("target_amount_minor > 0", name=op.f("ck_goals_target")),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], name=op.f("fk_goals_account_id_accounts")),
        sa.ForeignKeyConstraint(["member_id"], ["members.id"], name=op.f("fk_goals_member_id_members")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goals")),
    )
    with op.batch_alter_table("goals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_goals_deleted_at"), ["deleted_at"], unique=False)

    op.create_table(
        "goal_contributions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("goal_id", sa.Integer(), nullable=False),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("tz_offset_minutes", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], name=op.f("fk_goal_contributions_goal_id_goals")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goal_contributions")),
    )
    with op.batch_alter_table("goal_contributions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_goal_contributions_goal_id"), ["goal_id"], unique=False)

    op.create_table(
        "piggy_banks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("target_name", sa.String(length=120), nullable=False),
        sa.Column("target_amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("skin", sa.String(length=24), nullable=False),
        sa.Column("hide_amount", sa.Boolean(), nullable=False),
        sa.Column("goal_id", sa.Integer(), nullable=True),
        sa.Column("achieved_at", sa.DateTime(), nullable=True),
        sa.Column("celebrated", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="软删除时间（UTC）；NULL 表示未删除"),
        sa.CheckConstraint("kind IN ('one_time', 'long_term', 'shared')", name=op.f("ck_piggy_banks_kind")),
        sa.CheckConstraint(
            "status IN ('active', 'achieved', 'paused', 'abandoned')", name=op.f("ck_piggy_banks_status")
        ),
        sa.CheckConstraint("priority BETWEEN 0 AND 9", name=op.f("ck_piggy_banks_priority")),
        sa.CheckConstraint("target_amount_minor > 0", name=op.f("ck_piggy_banks_target")),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], name=op.f("fk_piggy_banks_goal_id_goals")),
        sa.ForeignKeyConstraint(["member_id"], ["members.id"], name=op.f("fk_piggy_banks_member_id_members")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_piggy_banks")),
    )
    with op.batch_alter_table("piggy_banks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_piggy_banks_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_piggy_banks_goal_id"), ["goal_id"], unique=False)

    op.create_table(
        "piggy_bank_deposits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("piggy_bank_id", sa.Integer(), nullable=False),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("tz_offset_minutes", sa.Integer(), nullable=False),
        sa.Column("source_account_id", sa.Integer(), nullable=True),
        sa.Column("transaction_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.CheckConstraint(
            "kind IN ('manual', 'auto', 'roundup', 'change', 'milestone', 'withdraw', 'settle')",
            name=op.f("ck_piggy_bank_deposits_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["piggy_bank_id"],
            ["piggy_banks.id"],
            name=op.f("fk_piggy_bank_deposits_piggy_bank_id_piggy_banks"),
        ),
        sa.ForeignKeyConstraint(
            ["source_account_id"],
            ["accounts.id"],
            name=op.f("fk_piggy_bank_deposits_source_account_id_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_piggy_bank_deposits_transaction_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_piggy_bank_deposits")),
    )
    with op.batch_alter_table("piggy_bank_deposits", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_piggy_bank_deposits_piggy_bank_id"), ["piggy_bank_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_piggy_bank_deposits_transaction_id"), ["transaction_id"], unique=False
        )

    op.create_table(
        "piggy_bank_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("piggy_bank_id", sa.Integer(), nullable=False),
        sa.Column("strategy", sa.String(length=24), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("roundup_unit_minor", sa.Integer(), nullable=False),
        sa.Column("fixed_amount_minor", sa.Integer(), nullable=False),
        sa.Column("percent_bps", sa.Integer(), nullable=False),
        sa.Column("category_ids", sa.Text(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("deduct_from_account", sa.Boolean(), nullable=False),
        sa.Column("last_run_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.CheckConstraint(
            "strategy IN ('roundup', 'daily_fixed', 'weekly_fixed', 'income_percent', 'monthly_surplus', 'category_trigger')",
            name=op.f("ck_piggy_bank_rules_strategy"),
        ),
        sa.CheckConstraint("fixed_amount_minor >= 0", name=op.f("ck_piggy_bank_rules_fixed")),
        sa.CheckConstraint("percent_bps BETWEEN 0 AND 10000", name=op.f("ck_piggy_bank_rules_percent")),
        sa.CheckConstraint("roundup_unit_minor > 0", name=op.f("ck_piggy_bank_rules_roundup_unit")),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_piggy_bank_rules_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["piggy_bank_id"], ["piggy_banks.id"], name=op.f("fk_piggy_bank_rules_piggy_bank_id_piggy_banks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_piggy_bank_rules")),
        sa.UniqueConstraint("piggy_bank_id", name="uq_piggy_bank_rules_bank"),
    )
    with op.batch_alter_table("piggy_bank_rules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_piggy_bank_rules_piggy_bank_id"), ["piggy_bank_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("piggy_bank_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_piggy_bank_rules_piggy_bank_id"))

    op.drop_table("piggy_bank_rules")
    with op.batch_alter_table("piggy_bank_deposits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_piggy_bank_deposits_transaction_id"))
        batch_op.drop_index(batch_op.f("ix_piggy_bank_deposits_piggy_bank_id"))

    op.drop_table("piggy_bank_deposits")
    with op.batch_alter_table("piggy_banks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_piggy_banks_goal_id"))
        batch_op.drop_index(batch_op.f("ix_piggy_banks_deleted_at"))

    op.drop_table("piggy_banks")
    with op.batch_alter_table("goal_contributions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_goal_contributions_goal_id"))

    op.drop_table("goal_contributions")
    with op.batch_alter_table("goals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_goals_deleted_at"))

    op.drop_table("goals")
    # ### end Alembic commands ###
