"""p6 insurance

迁移说明（自动生成后请手工补齐）
--------------------------------
* 为什么需要这次变更：
* 对既有数据的影响：
* 是否可回滚（downgrade 是否真的实现了）：

Revision ID: 98dfc6d2c979
Revises: 3dbc51d5db59
Create Date: 2026-10-01 22:02:49.004211
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "98dfc6d2c979"
down_revision: str | None = "3dbc51d5db59"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "insurance_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("city", sa.String(length=32), nullable=False),
        sa.Column("personal_rate_bps", sa.Integer(), nullable=False),
        sa.Column("employer_rate_bps", sa.Integer(), nullable=False),
        sa.Column("personal_to_account", sa.Boolean(), nullable=False),
        sa.Column("employer_to_account", sa.Boolean(), nullable=False),
        sa.Column("floor_base_minor", sa.Integer(), nullable=True),
        sa.Column("cap_base_minor", sa.Integer(), nullable=True),
        sa.Column("use_housing_base", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.CheckConstraint(
            "kind IN ('pension', 'medical', 'unemployment', 'injury', 'maternity', 'housing_fund', 'supplementary_fund', 'enterprise_annuity', 'critical_illness', 'other')",
            name=op.f("ck_insurance_items_kind"),
        ),
        sa.CheckConstraint(
            "employer_rate_bps BETWEEN 0 AND 10000", name=op.f("ck_insurance_items_employer_rate")
        ),
        sa.CheckConstraint(
            "personal_rate_bps BETWEEN 0 AND 10000", name=op.f("ck_insurance_items_personal_rate")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insurance_items")),
        sa.UniqueConstraint("kind", "city", name="uq_insurance_items_kind_city"),
    )
    op.create_table(
        "insurance_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=48), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("city", sa.String(length=32), nullable=False),
        sa.Column("employer", sa.String(length=80), nullable=False),
        sa.Column("social_base_minor", sa.Integer(), nullable=False),
        sa.Column("housing_base_minor", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="软删除时间（UTC）；NULL 表示未删除"),
        sa.CheckConstraint(
            "social_base_minor >= 0 AND housing_base_minor >= 0", name=op.f("ck_insurance_profiles_bases")
        ),
        sa.ForeignKeyConstraint(
            ["member_id"], ["members.id"], name=op.f("fk_insurance_profiles_member_id_members")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insurance_profiles")),
    )
    with op.batch_alter_table("insurance_profiles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_insurance_profiles_deleted_at"), ["deleted_at"], unique=False)

    op.create_table(
        "insurance_annual_statements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("expected_personal_minor", sa.Integer(), nullable=True),
        sa.Column("expected_employer_minor", sa.Integer(), nullable=True),
        sa.Column("expected_balance_minor", sa.Integer(), nullable=True),
        sa.Column("interest_minor", sa.Integer(), nullable=False),
        sa.Column("reconciled_at", sa.DateTime(), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["insurance_profiles.id"],
            name=op.f("fk_insurance_annual_statements_profile_id_insurance_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insurance_annual_statements")),
        sa.UniqueConstraint("profile_id", "year", name="uq_insurance_statements_year"),
    )
    with op.batch_alter_table("insurance_annual_statements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_insurance_annual_statements_profile_id"), ["profile_id"], unique=False
        )

    op.create_table(
        "insurance_withdrawals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.Date(), nullable=False),
        sa.Column("reason", sa.String(length=16), nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.CheckConstraint(
            "reason IN ('purchase', 'rent', 'retirement', 'medical', 'settlement', 'other')",
            name=op.f("ck_insurance_withdrawals_reason"),
        ),
        sa.CheckConstraint("amount_minor > 0", name=op.f("ck_insurance_withdrawals_amount")),
        sa.ForeignKeyConstraint(
            ["item_id"], ["insurance_items.id"], name=op.f("fk_insurance_withdrawals_item_id_insurance_items")
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["insurance_profiles.id"],
            name=op.f("fk_insurance_withdrawals_profile_id_insurance_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_insurance_withdrawals_transaction_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insurance_withdrawals")),
    )
    with op.batch_alter_table("insurance_withdrawals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_insurance_withdrawals_item_id"), ["item_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_insurance_withdrawals_profile_id"), ["profile_id"], unique=False)

    op.create_table(
        "insurance_contributions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("base_minor", sa.Integer(), nullable=False),
        sa.Column("raw_base_minor", sa.Integer(), nullable=False),
        sa.Column("personal_rate_bps", sa.Integer(), nullable=False),
        sa.Column("employer_rate_bps", sa.Integer(), nullable=False),
        sa.Column("personal_minor", sa.Integer(), nullable=False),
        sa.Column("employer_minor", sa.Integer(), nullable=False),
        sa.Column("to_account_minor", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=12), nullable=False),
        sa.Column("payroll_record_id", sa.Integer(), nullable=True),
        sa.Column("transaction_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.CheckConstraint("base_minor >= 0", name=op.f("ck_insurance_contributions_base")),
        sa.CheckConstraint(
            "personal_minor >= 0 AND employer_minor >= 0", name=op.f("ck_insurance_contributions_amounts")
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["insurance_items.id"],
            name=op.f("fk_insurance_contributions_item_id_insurance_items"),
        ),
        sa.ForeignKeyConstraint(
            ["payroll_record_id"],
            ["payroll_records.id"],
            name=op.f("fk_insurance_contributions_payroll_record_id_payroll_records"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["insurance_profiles.id"],
            name=op.f("fk_insurance_contributions_profile_id_insurance_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_insurance_contributions_transaction_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insurance_contributions")),
        sa.UniqueConstraint("profile_id", "period", "item_id", name="uq_insurance_contributions_unique"),
    )
    with op.batch_alter_table("insurance_contributions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_insurance_contributions_item_id"), ["item_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_insurance_contributions_period"), ["period"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_insurance_contributions_profile_id"), ["profile_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("insurance_contributions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_insurance_contributions_profile_id"))
        batch_op.drop_index(batch_op.f("ix_insurance_contributions_period"))
        batch_op.drop_index(batch_op.f("ix_insurance_contributions_item_id"))

    op.drop_table("insurance_contributions")
    with op.batch_alter_table("insurance_withdrawals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_insurance_withdrawals_profile_id"))
        batch_op.drop_index(batch_op.f("ix_insurance_withdrawals_item_id"))

    op.drop_table("insurance_withdrawals")
    with op.batch_alter_table("insurance_annual_statements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_insurance_annual_statements_profile_id"))

    op.drop_table("insurance_annual_statements")
    with op.batch_alter_table("insurance_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_insurance_profiles_deleted_at"))

    op.drop_table("insurance_profiles")
    op.drop_table("insurance_items")
    # ### end Alembic commands ###
