"""p1 debt repayment plan

迁移说明
--------
* 为什么需要这次变更：债务功能缺"还款计划"（分摊到每期的本金与利息）。
  只新增**两个参数列**（还款方式、期数），分摊表本身不落库 ——
  它完全由本金、年化利率、期数与方式推出，存一份就要在每次改债务时同步；
* 对既有数据的影响：新增列都带服务端默认值（``lump_sum`` / 1），
  既有债务的行为不变（仍按"到期一次性还清"展示计划）；
* 是否可回滚：可以。``downgrade`` 删掉这两列。

Revision ID: aaa215176dc4
Revises: 6c353d2fb395
Create Date: 2026-10-01 14:26:22.664738
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "aaa215176dc4"
down_revision: str | None = "6c353d2fb395"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("debts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("repayment_method", sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column("installments", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("debts", schema=None) as batch_op:
        batch_op.drop_column("installments")
        batch_op.drop_column("repayment_method")

    # ### end Alembic commands ###
