"""P2 asset snapshots daily stats day events institutions card artworks

迁移说明
--------
* 为什么需要这次变更：
    P2 需要"能画出来"的数据底座 —— 卡片墙的机构与卡面字典，
    以及时序图/日历的唯一数据源（每日快照 + 日结缓存）。
        - ``institutions``：机构字典。用**稳定键**而不是名称字符串关联账户，
          否则用户把"招商银行"改成"招行"就会让卡面褪色；
        - ``card_artworks``：卡面配方（渐变/纹理/光泽的 JSON），
          而不是位图 —— 任意尺寸与 DPI 下都清晰，也能随主题校准；
        - ``daily_stats``：每日汇总缓存。日历一次要画 371 天，
          逐日聚合流水是 371 次查询；且 ``anomaly_score``、
          ``entry_state``、分账优先的 ``top_category_id`` 都无法从单日流水直接推出；
        - ``asset_snapshots``：每日每账户收盘余额。净值曲线必须按日固化 ——
          新增或删除一笔流水会改变历史某天的余额，因此快照需要增量重算；
        - ``day_events``：当日事件日志（事件/心情/纪念日/备注/待办共用一张表，
          它们字段完全一致，差别只在 ``kind``）；
        - ``accounts`` 增加 ``brand_key`` / ``card_style`` / ``card_network`` / ``theme_tint``。

* 对既有数据的影响：
    **只增不删**。5 张新表 + accounts 的 4 个新列，全部带默认值，
    因此既有账户行不会因为 NOT NULL 而失败。
    注意：``daily_stats`` 与 ``asset_snapshots`` 初始为空，
    首次读取时会由 ``services/daily.py`` 按需回填（含历史区间），
    因此升级后日历与净值曲线会有一段"首次计算"的时间。

* 是否可回滚：
    是。downgrade 会删掉 5 张新表并移除 accounts 的 4 个列。
    回滚只会丢失**派生缓存**（可由流水重算）与用户自建的机构/卡面/事件，
    不会影响流水、账户、分类等原始账目。

Revision ID: b6671e31e806
Revises: 37970cc9629c
Create Date: 2026-10-01 11:44:36.412226
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b6671e31e806"
down_revision: str | None = "37970cc9629c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card_artworks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=32), nullable=False, comment="稳定键"),
        sa.Column("name", sa.String(length=48), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.Column("file_ref", sa.String(length=128), nullable=False),
        sa.Column("author", sa.String(length=64), nullable=False),
        sa.Column("license", sa.String(length=64), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_artworks")),
        sa.UniqueConstraint("key", name=op.f("uq_card_artworks_key")),
    )
    op.create_table(
        "daily_stats",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("income_minor", sa.BigInteger(), nullable=False),
        sa.Column("expense_minor", sa.BigInteger(), nullable=False),
        sa.Column("net_minor", sa.BigInteger(), nullable=False),
        sa.Column("net_worth_minor", sa.BigInteger(), nullable=False),
        sa.Column("transfer_in_minor", sa.BigInteger(), nullable=False),
        sa.Column("transfer_out_minor", sa.BigInteger(), nullable=False),
        sa.Column("tx_count", sa.Integer(), nullable=False),
        sa.Column("pending_count", sa.Integer(), nullable=False),
        sa.Column("entry_state", sa.String(length=16), nullable=False),
        sa.Column("entry_confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("top_category_id", sa.Integer(), nullable=True),
        sa.Column("anomaly_score", sa.Float(), nullable=False),
        sa.Column("event_count", sa.Integer(), nullable=False),
        sa.Column("has_attachment", sa.Boolean(), nullable=False),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.CheckConstraint(
            "entry_state IN ('none', 'logged', 'confirmed')", name=op.f("ck_daily_stats_entry_state_domain")
        ),
        sa.PrimaryKeyConstraint("date", name=op.f("pk_daily_stats")),
    )
    with op.batch_alter_table("daily_stats", schema=None) as batch_op:
        batch_op.create_index("ix_daily_stats_entry_state", ["entry_state"], unique=False)

    op.create_table(
        "day_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=96), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("attachments", sa.JSON(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="软删除时间（UTC）；NULL 表示未删除"),
        sa.CheckConstraint(
            "kind IN ('event', 'mood', 'anniversary', 'note', 'todo')",
            name=op.f("ck_day_events_day_event_kind_domain"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_day_events")),
    )
    with op.batch_alter_table("day_events", schema=None) as batch_op:
        batch_op.create_index("ix_day_events_date", ["date", "sort_order"], unique=False)
        batch_op.create_index(batch_op.f("ix_day_events_deleted_at"), ["deleted_at"], unique=False)

    op.create_table(
        "institutions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=32), nullable=False, comment="稳定键，如 cmb / alipay"),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False, comment="bank/wallet/broker/other"),
        sa.Column("brand_color", sa.String(length=16), nullable=False),
        sa.Column("logo_ref", sa.String(length=128), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="软删除时间（UTC）；NULL 表示未删除"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_institutions")),
    )
    with op.batch_alter_table("institutions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_institutions_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(
            "uq_institutions_key_active", ["key"], unique=True, sqlite_where=sa.text("deleted_at IS NULL")
        )

    op.create_table(
        "asset_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("balance_minor", sa.BigInteger(), nullable=False),
        sa.Column("net_worth_minor", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_asset_snapshots_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_snapshots")),
        sa.UniqueConstraint("snapshot_date", "account_id", name="uq_asset_snapshots_date_account"),
    )
    with op.batch_alter_table("asset_snapshots", schema=None) as batch_op:
        batch_op.create_index("ix_asset_snapshots_date", ["snapshot_date"], unique=False)

    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("brand_key", sa.String(length=32), nullable=False, comment="机构键"))
        batch_op.add_column(sa.Column("card_style", sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column("card_network", sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column("theme_tint", sa.String(length=16), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_column("theme_tint")
        batch_op.drop_column("card_network")
        batch_op.drop_column("card_style")
        batch_op.drop_column("brand_key")

    with op.batch_alter_table("asset_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_asset_snapshots_date")

    op.drop_table("asset_snapshots")
    with op.batch_alter_table("institutions", schema=None) as batch_op:
        batch_op.drop_index("uq_institutions_key_active", sqlite_where=sa.text("deleted_at IS NULL"))
        batch_op.drop_index(batch_op.f("ix_institutions_deleted_at"))

    op.drop_table("institutions")
    with op.batch_alter_table("day_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_day_events_deleted_at"))
        batch_op.drop_index("ix_day_events_date")

    op.drop_table("day_events")
    with op.batch_alter_table("daily_stats", schema=None) as batch_op:
        batch_op.drop_index("ix_daily_stats_entry_state")

    op.drop_table("daily_stats")
    op.drop_table("card_artworks")
    # ### end Alembic commands ###
