"""p1 recurring budgets debts and p3 asset ohlc

迁移说明
--------
* 为什么需要这次变更：收尾 P1 未完成的三块功能（周期记账、预算、债务与
  应收应付）并启动 P3（净值 K 线），共新增 5 张表；
* 对既有数据的影响：**无**。只新增表，不修改也不删除任何既有列；
  所有非空列都带服务端默认值，老账本升级后行为完全不变；
* 是否可回滚：可以。``downgrade`` 逐一删除这 5 张表。
  代价是丢掉周期规则、预算与债务记录（这些不是流水，删了不会影响账目本身；
  由周期记账生成的流水仍留在 transactions 里，不会被一起删掉）。

Revision ID: cc8294c3ca9b
Revises: b6671e31e806
Create Date: 2026-10-01 13:10:15.959244
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cc8294c3ca9b"
down_revision: str | None = "b6671e31e806"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_ohlc",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("period", sa.String(length=8), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("open_minor", sa.Integer(), nullable=False),
        sa.Column("high_minor", sa.Integer(), nullable=False),
        sa.Column("low_minor", sa.Integer(), nullable=False),
        sa.Column("close_minor", sa.Integer(), nullable=False),
        sa.Column("volume_minor", sa.Integer(), nullable=False),
        sa.Column("tx_count", sa.Integer(), nullable=False),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.CheckConstraint("period IN ('day', 'week', 'month', 'year')", name=op.f("ck_asset_ohlc_period")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_ohlc")),
        sa.UniqueConstraint("period", "period_start", name="uq_asset_ohlc_period_start"),
    )
    with op.batch_alter_table("asset_ohlc", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_asset_ohlc_period_start"), ["period_start"], unique=False)

    op.create_table(
        "budgets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=12), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("period", sa.String(length=12), nullable=False),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("rollover", sa.Boolean(), nullable=False),
        sa.Column("carryover_minor", sa.Integer(), nullable=False),
        sa.Column("alert_threshold", sa.Float(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="软删除时间（UTC）；NULL 表示未删除"),
        sa.CheckConstraint(
            "period IN ('weekly', 'monthly', 'quarterly', 'yearly', 'custom')", name=op.f("ck_budgets_period")
        ),
        sa.CheckConstraint("scope IN ('total', 'category')", name=op.f("ck_budgets_scope")),
        sa.CheckConstraint("amount_minor >= 0", name=op.f("ck_budgets_amount")),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name=op.f("fk_budgets_category_id_categories")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budgets")),
    )
    with op.batch_alter_table("budgets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_budgets_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(
            "uq_budgets_active_scope",
            ["scope", "category_id"],
            unique=True,
            sqlite_where=sa.text("deleted_at IS NULL AND enabled = 1"),
        )

    op.create_table(
        "debts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False, comment="lend=借出 borrow=借入"),
        sa.Column("counterparty", sa.String(length=64), nullable=False),
        sa.Column("principal_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("mirror_account_id", sa.Integer(), nullable=True, comment="承载这笔债务的应收/应付账户"),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("annual_rate_bps", sa.Integer(), nullable=False, comment="年化利率（基点，1bp = 0.01%）"),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("settled_at", sa.Date(), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="软删除时间（UTC）；NULL 表示未删除"),
        sa.CheckConstraint("kind IN ('lend', 'borrow')", name=op.f("ck_debts_kind")),
        sa.CheckConstraint("status IN ('active', 'settled', 'written_off')", name=op.f("ck_debts_status")),
        sa.CheckConstraint("principal_minor >= 0", name=op.f("ck_debts_principal")),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], name=op.f("fk_debts_account_id_accounts")),
        sa.ForeignKeyConstraint(
            ["mirror_account_id"], ["accounts.id"], name=op.f("fk_debts_mirror_account_id_accounts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_debts")),
    )
    with op.batch_alter_table("debts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_debts_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_debts_due_date"), ["due_date"], unique=False)

    op.create_table(
        "recurring_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False, comment="规则名，如「房租」"),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False, comment="expense/income/transfer"),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("to_account_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("payee", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("frequency", sa.String(length=12), nullable=False),
        sa.Column("interval", sa.Integer(), nullable=False, comment="每 N 个周期一次"),
        sa.Column("by_month_day", sa.Integer(), nullable=True),
        sa.Column("by_weekday", sa.Integer(), nullable=True, comment="0=周日"),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("next_due_date", sa.Date(), nullable=True),
        sa.Column("last_posted_on", sa.Date(), nullable=True),
        sa.Column("auto_post", sa.Boolean(), nullable=False),
        sa.Column("lead_days", sa.Integer(), nullable=False),
        sa.Column("generated_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="软删除时间（UTC）；NULL 表示未删除"),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_recurring_rules_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name=op.f("fk_recurring_rules_category_id_categories")
        ),
        sa.ForeignKeyConstraint(
            ["to_account_id"], ["accounts.id"], name=op.f("fk_recurring_rules_to_account_id_accounts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recurring_rules")),
    )
    with op.batch_alter_table("recurring_rules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recurring_rules_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_recurring_rules_next_due_date"), ["next_due_date"], unique=False)

    op.create_table(
        "debt_payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("debt_id", sa.Integer(), nullable=False),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("principal_minor", sa.Integer(), nullable=False),
        sa.Column("interest_minor", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("tz_offset_minutes", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("transaction_id", sa.Integer(), nullable=True, comment="同时记的那笔流水"),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="最后修改时间（UTC）"),
        sa.CheckConstraint("amount_minor >= 0", name=op.f("ck_debt_payments_amount")),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_debt_payments_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(["debt_id"], ["debts.id"], name=op.f("fk_debt_payments_debt_id_debts")),
        sa.ForeignKeyConstraint(
            ["transaction_id"], ["transactions.id"], name=op.f("fk_debt_payments_transaction_id_transactions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_debt_payments")),
    )
    with op.batch_alter_table("debt_payments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_debt_payments_debt_id"), ["debt_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("debt_payments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_debt_payments_debt_id"))

    op.drop_table("debt_payments")
    with op.batch_alter_table("recurring_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recurring_rules_next_due_date"))
        batch_op.drop_index(batch_op.f("ix_recurring_rules_deleted_at"))

    op.drop_table("recurring_rules")
    with op.batch_alter_table("debts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_debts_due_date"))
        batch_op.drop_index(batch_op.f("ix_debts_deleted_at"))

    op.drop_table("debts")
    with op.batch_alter_table("budgets", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_budgets_active_scope", sqlite_where=sa.text("deleted_at IS NULL AND enabled = 1")
        )
        batch_op.drop_index(batch_op.f("ix_budgets_deleted_at"))

    op.drop_table("budgets")
    with op.batch_alter_table("asset_ohlc", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_asset_ohlc_period_start"))

    op.drop_table("asset_ohlc")
    # ### end Alembic commands ###
